services:
  - type: web
    name: agrisense-backend
    env: node
    plan: free
    buildCommand: corepack enable && yarn install --immutable && yarn build && node scripts/run-migration.js
    startCommand: yarn start:prod
    envVars:
      - key: NODE_ENV
        value: production
      - key: TYPEORM_SYNCHRONIZE
        value: "true"

      # PostgreSQL (external, e.g. Neon)
      - key: DATABASE_URL
        sync: false
      - key: DATABASE_SSL
        value: "true"

      # Redis (Upstash â€“ external)
      - key: REDIS_URL
        sync: false

      - key: JWT_SECRET
        generateValue: true
